# Generated by Django 4.1.3 on 2024-05-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_website_github_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
